### ISSUE TITLE
Goodevening i have this isue with the pioneer vsx 922

### ISSUE THREAD

**Issue by BitjeMaster** [rwifall/pioneer-receiver-notes#1]
[6/3/2020, 10:45:16 PM] [My Pioneer AVR] Get power status
[6/3/2020, 10:45:16 PM] [My Pioneer AVR] Get mute status
[6/3/2020, 10:45:16 PM] [My Pioneer AVR] Get volume status
[6/3/2020, 10:45:16 PM] TypeError: this.volumeStatus is not a function
    at pioneerAvrAccessory.getVolume (/usr/lib/node_modules/homebridge-pioneer-avr/index.js:254:10)
    at Volume.emit (events.js:198:13)
    at Volume.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Volume.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:462:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1143:10)
    at HAPServer.emit (events.js:198:13)
    at HAPServer.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:756:12)

**Comment by rwifall** [comment]
Hi, you are posting your issue on the wrong project.  This project is only notes about how to integrate with a Pioneer receiver.  You need to post your issue on the project that you are using that is having the error.
It looks like you are using homebridge-pioneer-avr.  If that is the case you need to post your issue here: [https://github.com/kazcangi/homebridge-pioneer-avr/issues](https://github.com/kazcangi/homebridge-pioneer-avr/issues)
